# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEdit(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 441)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.verticalLayout.addWidget(self.roastLineEdit)
        self.grindLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.grindLineEdit.setObjectName("grindLineEdit")
        self.verticalLayout.addWidget(self.grindLineEdit)
        self.descriptionTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.descriptionTextEdit)
        self.priceSpinBox = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.verticalLayout.addWidget(self.priceSpinBox)
        self.volumeSpinBox = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.volumeSpinBox.setObjectName("volumeSpinBox")
        self.verticalLayout.addWidget(self.volumeSpinBox)
        self.saveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nameLineEdit.setPlaceholderText(_translate("MainWindow", "название кофе"))
        self.roastLineEdit.setPlaceholderText(_translate("MainWindow", "степень обжарки"))
        self.grindLineEdit.setPlaceholderText(_translate("MainWindow", "тип кофе"))
        self.descriptionTextEdit.setPlaceholderText(_translate("MainWindow", "описание"))
        self.priceSpinBox.setPlaceholderText(_translate("MainWindow", "цена"))
        self.volumeSpinBox.setPlaceholderText(_translate("MainWindow", "тип упаковки"))
        self.saveButton.setText(_translate("MainWindow", "сохранить"))
